### ISSUE TITLE
Unrecognized argument - local rank when training

### ISSUE THREAD

**Issue by PulkitAgr113** [kakaobrain/honeybee#24]
Hi, I was trying to train the Honeybee-C-13B-M576 pre-trained checkpoint on the ScienceQA dataset. I am running the following script:
```
deepspeed ./train.py \
    --config-name=finetune output_dir=${ft_output_dir} pretrained_ckpt=${pretrained_ckpt} \
    'data_config/train_dataset=[sqa]' \
    data_config.train_cfg.sampling_weights=[1.0] \
    2>&1 | tee ${ft_output_dir}/train.log
```

However, this raises the following error:
```
usage: train.py [--help] [--hydra-help] [--version] [--cfg {job,hydra,all}] [--resolve] [--package PACKAGE] [--run] [--multirun]
                [--shell-completion] [--config-path CONFIG_PATH] [--config-name CONFIG_NAME] [--config-dir CONFIG_DIR]
                [--experimental-rerun EXPERIMENTAL_RERUN] [--info [{all,config,defaults,defaults-tree,plugins,searchpath}]]
                [overrides ...]
train.py: error: unrecognized arguments: --local_rank=0
```

This is faced irrespective of the number of GPUs being used. I have used the given requirements file to create a new environment on Python 3.10 and Pytorch 2.0.1. In addition to the given requirements, I also installed opencompass and installed opencv-python-headless instead of opencv-python, since there were some other errors before this. I have been able to successfully run inference, but the training code gives the above error. Kindly look into this issue (if there's some other information needed, then please inform me about the same).

**Comment by khanrc** [comment]
It looks like an issue of deepspeed. What is your deepspeed version?

**Comment by PulkitAgr113** [comment]
The deepspeed version is 0.10.0, the same as that given in the requirements.txt file. I also tried updating the deepspeed version to the latest one (0.14.2), but the same error was raised.

This is the output of `ds_report`:
```
[2024-06-10 08:57:11,949] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/opt/conda/envs/honeybee/lib/python3.10/site-packages/torch']
torch version .................... 2.0.1+cu117
deepspeed install path ........... ['/opt/conda/envs/honeybee/lib/python3.10/site-packages/deepspeed']
deepspeed info ................... 0.10.0, unknown, unknown
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 11.7
deepspeed wheel compiled w. ...... torch 2.0, cuda 11.7
```

**Comment by PulkitAgr113** [comment]
I think it's some problem with hydra and torch.distributed being used together. I don't have a lot of experience with this, but the same issue is discussed [here](https://github.com/facebookresearch/hydra/issues/2038). Is there some change possible to handle this?

**Comment by PulkitAgr113** [comment]
Hi, I was able to resolve this issue by passing `--no_local_rank` as an argument when using deepspeed.

However, I am stuck with another problem. I was trying to do LoRA fine-tuning instead (so I changed use_lora to True in finetune.yaml). Everything else remains the same. However, I face the following error when loading the PEFT model.

```
Traceback (most recent call last):
  File "/workspace/honeybee/./train.py", line 193, in main
    lora_model = get_peft_model(model, peft_config)
  File "/opt/conda/envs/honeybee/lib/python3.10/site-packages/peft/mapping.py", line 166, in get_peft_model
    return PeftModel(model, peft_config, adapter_name=adapter_name, autocast_adapter_dtype=autocast_adapter_dtype)
  File "/opt/conda/envs/honeybee/lib/python3.10/site-packages/peft/peft_model.py", line 148, in __init__
    self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
  File "/opt/conda/envs/honeybee/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 139, in __init__
    super().__init__(model, config, adapter_name)
  File "/opt/conda/envs/honeybee/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 166, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "/opt/conda/envs/honeybee/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 411, in inject_adapter
    parent, target, target_name = _get_submodules(model, key)
  File "/opt/conda/envs/honeybee/lib/python3.10/site-packages/peft/utils/other.py", line 309, in _get_submodules
    parent = model.get_submodule(".".join(key.split(".")[:-1]))
  File "/opt/conda/envs/honeybee/lib/python3.10/site-packages/torch/nn/modules/module.py", line 658, in get_submodule
    raise AttributeError(mod._get_name() + " has no "
AttributeError: ModulesToSaveWrapper has no attribute `model`. Did you mean: '_return_value'?
```

I have tried updating peft, torch, transformers, accelerate, but the error still persists. Is there some way to solve this?

**Comment by wykang** [comment]
@PulkitAgr113 Due to the internal logic, you may also change the `train.module_to_update` option when you train the model using LoRA. For example, the train argument dict in the finetune.yaml should be as follows:
```
train:
  mode: sft
  module_to_update:
    - abstractor
 ```

**Comment by PulkitAgr113** [comment]
Thanks, that worked!

**Comment by PulkitAgr113** [comment]
Hi, when I try to load the model after fine-tuning, I receive the following error:

```
Traceback (most recent call last):
  File "/workspace/honeybee/eval_honeybee.py", line 60, in <module>
    model, tokenizer, processor = get_model(args.model_path, use_bf16=True)  
  File "/workspace/honeybee/pipeline/interface.py", line 72, in get_model
    model = load_model(pretrained_ckpt, use_bf16, load_in_8bit)
  File "/workspace/honeybee/pipeline/interface.py", line 50, in load_model
    model = HoneybeeForConditionalGeneration.from_pretrained(
  File "/opt/conda/envs/honeybee/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3502, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/opt/conda/envs/honeybee/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3945, in _load_pretrained_model
    error_msgs += _load_state_dict_into_model(model_to_load, state_dict, start_prefix)
  File "/opt/conda/envs/honeybee/lib/python3.10/site-packages/transformers/modeling_utils.py", line 626, in _load_state_dict_into_model
    load(model_to_load, state_dict, prefix=start_prefix)
  File "/opt/conda/envs/honeybee/lib/python3.10/site-packages/transformers/modeling_utils.py", line 624, in load
    load(child, state_dict, prefix + name + ".")
  File "/opt/conda/envs/honeybee/lib/python3.10/site-packages/transformers/modeling_utils.py", line 620, in load
    module._load_from_state_dict(*args)
  File "/workspace/honeybee/honeybee/projectors/projectors.py", line 107, in _load_from_state_dict
    pos_emb = state_dict["abstractor.pos_emb"]
KeyError: 'abstractor.pos_emb'
```

Is there something missing here? I am simply using the `get_model` function from `pipeline.interface`. My code works fine if I use one of the pre-trained or fine-tuned checkpoints instead
